services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    env_file: .env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inception
    restart: on-failure

  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    env_file: .env
    depends_on:
      - mariadb
    volumes:
      - wp_files:/var/www/html
    networks:
      - inception
    restart: on-failure

  nginx:
    build: ./requirements/nginx
    image: nginx
    container_name: nginx
    env_file: .env
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wp_files:/var/www/html:ro
    networks:
      - inception
    restart: on-failure

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      device: /home/ppaula-s/data/mariadb
      o: bind
  wp_files:
    driver: local
    driver_opts:
      type: none
      device: /home/ppaula-s/data/wordpress
      o: bind

networks:
  inception:
    driver: bridge
